name: Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

env:
  PHP_VERSION: 8.2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: "${{ env.PHP_VERSION }}"
        tools: composer-require-checker
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Validate Filesystem skeleton
      run: vendor/bin/pds-skeleton validate

    - name: Check dependencies are properly required
      run: composer-require-checker check --config-file=composer-require-checker.json --ignore-parse-errors

    - name: Run test suite
      run: composer run-script test
